version: '3.4'

services:

  data-server:
    image: "nsidc/snow-today-webapp-server:${SERVER_VERSION:-latest}"
    volumes:
      - "${STORAGE_DIR}/cogs:/usr/share/nginx/html/cogs:ro"
      - "${STORAGE_DIR}/plots:/usr/share/nginx/html/plots:ro"
      # Mount dynamic legends underneath the static legends dir
      - "${STORAGE_DIR}/dynamic_legends:/usr/share/nginx/html/legends/dynamic:ro"
    ports:
      - "80:80"
      - "443:443"
    logging:
      options:
        max-size: "10m"
        max-file: "10"


  ingest:
    image: "nsidc/snow-today-webapp-server-ingest:${SERVER_VERSION:-latest}"
    volumes:
      - "${STORAGE_DIR}/incoming:/storage/incoming:ro"
      - "${STORAGE_DIR}/cogs:/storage/cogs:rw"
      - "${STORAGE_DIR}/plots:/storage/plots:rw"
      - "${STORAGE_DIR}/dynamic_legends:/storage/dynamic_legends:rw"
    environment:
      # Use a generic storage dir within the container
      STORAGE_DIR: "/storage"
    restart: 'no'
    logging:
      options:
        max-size: "10m"
        max-file: "10"
