version: '3.4'

services:

  data-server:
    image: "nsidc/snow-today-webapp-server:dev"
    build: .
    volumes:
      - "./static/variables.json:/usr/share/nginx/html/variables.json:ro"
      - "./static/colormaps.json:/usr/share/nginx/html/colormaps.json:ro"
    restart: "on-failure"


  ingest:
    image: "nsidc/snow-today-webapp-server-ingest:dev"
    build:
      context: "."
      dockerfile: "Dockerfile.ingest"
    volumes:
      - "./snow_today_webapp_ingest:/snow-today-webapp-server-ingest/snow_today_webapp_ingest:ro"
      - "./static:/snow-today-webapp-server-ingest/static:rw"
      - "./schema:/snow-today-webapp-server-ingest/schema:ro"
