version: '3.4'

x-common: &common
  logging:
    options:
      max-size: "10m"
      max-file: "10"


services:

  data-server:
    image: "nsidc/snow-today-webapp-server:${SERVER_VERSION:-latest}"
    container_name: "data-server"
    <<: *common
    volumes:
      - "${STORAGE_DIR:?STORAGE_DIR must be set}/live:/usr/share/nginx/html:ro"
    ports:
      - "80:80"
      - "443:443"


  ingest:
    image: "nsidc/snow-today-webapp-server-ingest:${SERVER_VERSION:-latest}"
    container_name: "ingest"
    <<: *common
    volumes:
      - "${STORAGE_DIR:?STORAGE_DIR must be set}/incoming:/storage/incoming:ro"
      - "${STORAGE_DIR:?STORAGE_DIR must be set}/ingest-wip:/storage/ingest-wip:rw"
    environment:
      # Timezone is critical because the ingest code cares about the date for
      # generating dynamic legends
      TZ: "America/Denver"
      # Use a generic storage dir within the container
      STORAGE_DIR: "/storage"
    restart: 'no'
    logging:
      options:
        max-size: "10m"
        max-file: "10"
