name: snow-today 
channels:
  - conda-forge
  - nodefaults
platforms:
  - osx-64
  - linux-64
dependencies:
  - python ~=3.10.5


  ###########################################
  # Runtime dependencies
  ###########################################
  - click ~=8.1
  # For making Cloud-Optimized GeoTIFFs:
  - gdal ~=3.5.1
  # For Shapefile -> GeoJSON conversion:
  - geopandas ~=0.11.1
  # For making legends:
  - matplotlib-base ~=3.5
  # For comparing JSON changes:
  - deepdiff ~=5.8
  # For simple logging:
  - loguru ~=0.6.0



  ###########################################
  # Development & testing dependencies
  ###########################################
  - conda-lock ~=2.3
  - pre-commit
  - invoke ~=1.7
  - mypy ~=0.971

  # For schema validation:
  # TODO: is this really a runtime dep??
  - jsonschema ~=4.9.1
  # For TypedDicts with optional keys. REMOVE after upgrading to Python 3.11
  - typing-extensions ~=4.3.0

  # TODO:
  # - pytest ~=7.1
