name: snow-today 
channels:
  - conda-forge
  - nodefaults
platforms:
  - linux-64
  # Temporarily disabled osx due to weird JSON parsing errors when enabled.
  # - osx-64
dependencies:
  - python ~=3.10.5


  ###########################################
  # Runtime dependencies
  ###########################################
  - click ~=8.1
  # For adding a --log-level parameter to CLI:
  - click-loglevel ~=0.5.0
  # For making Cloud-Optimized GeoTIFFs (pinned more strictly because GDAL is
  # brittle):
  - gdal ~=3.5.1
  # For making legends:
  - matplotlib-base ~=3.8
  # For comparing JSON changes:
  - deepdiff ~=5.8
  # For simple logging:
  - loguru ~=0.7.2



  ###########################################
  # Development & testing dependencies
  ###########################################
  - conda-lock ~=2.5
  - pre-commit
  - invoke ~=2.2
  - mypy ~=1.8

  # For schema validation:
  - jsonschema ~=4.20
  - types-jsonschema ~=4.20
  # For TypedDicts with optional keys. REMOVE after upgrading to Python 3.11
  - typing-extensions ~=4.9

  # TODO:
  # - pytest ~=7.1
