name: snow-today 
channels:
  - conda-forge
  - nodefaults
platforms:
  - osx-64
  - linux-64
dependencies:
  - python ~=3.10.5


  ###########################################
  # Runtime dependencies
  ###########################################
  - click ~=8.1
  # For making Cloud-Optimized GeoTIFFs:
  - gdal ~=3.5.1
  # For Shapefile -> GeoJSON conversion:
  - geopandas ~=0.11.1
  # For making legends:
  - matplotlib-base ~=3.5
  # For comparing JSON changes:
  - deepdiff ~=5.8
  # For simple logging:
  - loguru ~=0.6.0



  ###########################################
  # Development & testing dependencies
  ###########################################
  - conda-lock ~=2.3
  - invoke ~=1.7
  - black ~=22.6.0
  - isort ~=5.10
  - mypy ~=0.971
  - flake8 ~=5.0.4
  - flake8-bugbear ~=22.8
  - flake8-comprehensions ~=3.10
  - flake8-docstrings ~=1.6
  - flake8-use-fstring ~=1.4
  # For schema validation:
  - jsonschema ~=4.9.1
  # For TypedDicts with optional keys. REMOVE after upgrading to Python 3.11
  - typing-extensions ~=4.3.0

  # TODO:
  # - pytest ~=7.1
  # - shellcheck ~=0.8.0
