name: snow-today 
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python ~=3.10.5
  # For making Cloud-Optimized GeoTIFFs:
  - gdal ~=3.5.1
  # For schema validation:
  - jsonschema ~=4.9.1
  # For Shapefile -> GeoJSON conversion:
  - geopandas ~=0.11.1
