[tool.mypy]
python_version = "3.10"
incremental = true
show_error_codes = true
check_untyped_defs = true
warn_unreachable = true

# Modules without type stubs:
[[tool.mypy.overrides]]
module = [
  "matplotlib.*",
  "deepdiff.*",
  "invoke.*",
  "osgeo.*",
  "geopandas.*",
]
ignore_missing_imports = true

# Stricter rules for our own code than our dependencies
# TODO: Enable!!!
[[tool.mypy.overrides]]
module = "snow_today_webapp_ingest.*"
# disallow_untyped_defs = true
# disallow_incomplete_defs = true


[tool.black]
target-version = ['py310']
skip-string-normalization = true


[tool.ruff]
target-version = "py310"

select = [
  "F",    # pyflakes
  "E",    # pycodestyle warnings
  "W",    # pycodestyle warnings
  "C4",   # flake8-comprehensions
  "C90",  # mccabe
  "I",    # isort
  "N",    # pep8-naming
  "D",    # pydocstyle
  "UP",   # pyupgrade
  "YTT",  # flake8-2020
  "B",    # flake8-bugbear
  "A",    # flake8-builtins
  "T10",  # flake8-debugger
  "RUF",  # ruff-specific rules
]

ignore = [
  # D1: Ignore errors requiring docstrings on everything.
  # D203: "1 blank line required before class docstring"
  # D213: "Multi-line docstring summary should start at the second line"
  # E731: Lambda assignments are OK, use your best judgement.
  # RUF010: !a, !r, !s are too magical for me.
  "D1", "D203", "D213", "E731", "RUF010",
]

[tool.ruff.isort]
known-first-party = ["snow_today_webapp_ingest"]

[tool.ruff.mccabe]
max-complexity = 8

[tool.ruff.flake8-quotes]
inline-quotes = "double"
