# NOTE: It would be really nice if the state abbreviation was included on the feature
# data, but it's not!
# NOTE: It would be really nice if the input data only included the needed regions, but
# it may contain any.
STATES_BY_ABBREV = {
    'AK': 'Alaska',
    'AL': 'Alabama',
    'AR': 'Arkansas',
    'AZ': 'Arizona',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DC': 'District of Columbia',
    'DE': 'Delaware',
    'FL': 'Florida',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'IA': 'Iowa',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'MA': 'Massachusetts',
    'MD': 'Maryland',
    'ME': 'Maine',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MO': 'Missouri',
    'MS': 'Mississippi',
    'MT': 'Montana',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'NE': 'Nebraska',
    'NM': 'New Mexico',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NV': 'Nevada',
    'NY': 'New York',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VA': 'Virginia',
    'VT': 'Vermont',
    'WA': 'Washington',
    'WI': 'Wisconsin',
    'WY': 'Wyoming',
}
ENABLED_STATE_ABBREVS = [
    'AZ',
    'CA',
    'CO',
    'ID',
    'MT',
    'NE',
    'NM',
    'NV',
    'OR',
    'SD',
    'UT',
    'WA',
    'WY',
]
STATE_ABBREVS = {v: k for k, v in STATES_BY_ABBREV.items()}
STATES_ENABLED = {v for k, v in STATES_BY_ABBREV.items() if k in ENABLED_STATE_ABBREVS}
