#!/bin/bash
set -euo pipefail

ENVIRONMENT="$1"

THIS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT_DIR="$(dirname "$THIS_DIR")"

VERSION_FILE="$REPO_ROOT_DIR/VERSION.env"

source /etc/profile.d/envvars.sh

cd "$REPO_ROOT_DIR"

if [ "$ENVIRONMENT" = "integration" ]; then
    version_desc="latest"
    VERSION_FILE="$REPO_ROOT_DIR/VERSION.latest.env"
else
    version_desc="production"
fi

echo "Using $version_desc versions in $ENVIRONMENT..."
cat "$VERSION_FILE"
source "$VERSION_FILE"

# Pull down new images
ln -sf docker-compose.live.yml docker-compose.override.yml
docker-compose pull

# Cleanup old containers
docker-compose down --remove-orphans

# Start the server
docker-compose up -d data-server

# Cleanup
docker system prune -af
