project:
  type: "website"


website:
  title: "Snow Today Webapp Server Docs"
  site-url: "https://nsidc.github.io/snow-today-webapp-server"
  repo-url: "https://github.com/nsidc/snow-today-webapp-server"
  repo-actions:
    - "edit"
    - "source"
    - "issue"

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; NSIDC"

  sidebar:
    background: "#eee"
    style: "docked"
    search: true
    contents:
      - section: "Interfaces"
        contents: "interfaces"
      - text: "Ingest"
        href: "index.md"
        contents:
          - text: "TODO"
            href: "index.md"


format:
  html:
    theme: "cosmo"
    css: "styles.css"
    toc: true
