import os
from pathlib import Path

STORAGE_DIR = Path(os.environ['STORAGE_DIR'])


###############################################
# Static data in this repo
###############################################
REPO_ROOT_DIR = Path(__file__).parent.parent.parent.absolute()

# TODO: Move schemas in to ingest package?
SCHEMAS_DIR = REPO_ROOT_DIR / 'schema'

# Where static content is stored
REPO_DATA_DIR = REPO_ROOT_DIR / 'data'
# REPO_SHAPES_DIR = REPO_DATA_DIR / 'shapes'

# Index data
# REGION_INDEX_FP = REPO_DATA_DIR / 'regions.json'
VARIABLES_INDEX_FP = REPO_DATA_DIR / 'variables.json'


###############################################
# Outputs generated by this program
###############################################

# Where this program will write temporary directories to store WIP ingest outputs
INGEST_WIP_DIR = STORAGE_DIR / 'ingest-wip'

# These are strings instead of Paths because they will be created inside temporary
# directories within INGEST_WIP_DIR
OUTPUT_REGIONS_SUBDIR = 'regions'
OUTPUT_COGS_SUBDIR = 'cogs'
OUTPUT_DYNAMIC_LEGENDS_SUBDIR = 'dynamic_legends'
OUTPUT_PLOTS_SUBDIR = 'plots'
OUTPUT_POINTS_SUBDIR = 'points'


###############################################
# Inputs generated by upstream program
###############################################

INCOMING_DIR = STORAGE_DIR / 'incoming'
INCOMING_SWE_DIR = INCOMING_DIR / 'snow-water-equivalent'
INCOMING_SSP_DIR = INCOMING_DIR / 'snow-surface-properties'

INCOMING_REGIONS_DIR = INCOMING_SSP_DIR / 'regions'
INCOMING_TIF_DIR = INCOMING_SSP_DIR / 'geotiffs'
INCOMING_SHAPE_DIR = INCOMING_SSP_DIR / 'shapes'
INCOMING_PLOT_CSV_DIR = INCOMING_SSP_DIR / 'plot_csv'
