import os
from pathlib import Path

# IMPORTANT: Defaults to tmp to allow e.g. --help, but is checked by the CLI command
# before running anything.
storage_dir_default = "/tmp/snow-today-webapp-ingest"
STORAGE_DIR = Path(os.environ.get("STORAGE_DIR", storage_dir_default))


###############################################
# Static data in this repo
###############################################
REPO_ROOT_DIR = Path(__file__).parent.parent.parent.absolute()

# Dir where static data is stored
REPO_STATIC_DATA_DIR = REPO_ROOT_DIR / 'static'
REPO_STATIC_COLORMAPS_INDEX_FP = REPO_STATIC_DATA_DIR / 'common' / 'colormaps.json'
REPO_STATIC_SSP_VARIABLES_INDEX_FP = (
    REPO_STATIC_DATA_DIR / 'snow-surface-properties' / 'variables.json'
)
REPO_STATIC_SWE_VARIABLES_INDEX_FP = (
    REPO_STATIC_DATA_DIR / 'snow-water-equivalent' / 'variables.json'
)

# Dir where schemas are stored
# TODO: Move schemas in to ingest package?
REPO_STATIC_SCHEMAS_DIR = REPO_ROOT_DIR / 'schema'


###############################################
# Outputs generated by this program
###############################################

# Where this program will write temporary directories to store WIP ingest outputs
INGEST_WIP_DIR = STORAGE_DIR / 'ingest-wip'

# These are relative Paths because they will be created inside temporary WIP
# directories, so we don't know their parents yet.
# TODO: This is a really unreadable way to express directory structure.
OUTPUT_REGIONS_SUBDIR = Path('regions')
OUTPUT_REGIONS_SHAPES_SUBDIR = OUTPUT_REGIONS_SUBDIR / "shapes"
OUTPUT_REGIONS_COGS_SUBDIR = OUTPUT_REGIONS_SUBDIR / "cogs"
OUTPUT_LEGENDS_SUBDIR = Path('legends')
OUTPUT_PLOTS_SUBDIR = Path('plots')
OUTPUT_POINTS_SUBDIR = Path('points')

# Where the live data goes after ingest is successful
OUTPUT_LIVE_DIR = STORAGE_DIR / 'live'
OUTPUT_LIVE_SSP_DIR = OUTPUT_LIVE_DIR / 'snow-surface-properties'
OUTPUT_LIVE_SWE_DIR = OUTPUT_LIVE_DIR / 'snow-water-equivalent'
OUTPUT_LIVE_COMMON_DIR = OUTPUT_LIVE_DIR / 'common'

# Every successful ingest also creates a backup
OUTPUT_BKP_DIR = STORAGE_DIR / 'bkp'

###############################################
# Inputs generated by upstream program
###############################################

INCOMING_DIR = STORAGE_DIR / 'incoming'

INCOMING_SSP_DIR = INCOMING_DIR / 'snow-surface-properties'
INCOMING_REGIONS_DIR = INCOMING_SSP_DIR / 'regions'
INCOMING_REGIONS_ROOT_JSON = INCOMING_REGIONS_DIR / 'root.json'
INCOMING_REGIONS_COLLECTIONS_JSON = INCOMING_REGIONS_DIR / 'collections.json'
INCOMING_TIF_DIR = INCOMING_SSP_DIR / 'geotiffs'
INCOMING_SHAPES_DIR = INCOMING_SSP_DIR / 'shapes'
INCOMING_PLOT_JSON_DIR = INCOMING_SSP_DIR / 'plots'

INCOMING_SWE_DIR = INCOMING_DIR / 'snow-water-equivalent'
INCOMING_SWE_POINTS_DIR = INCOMING_SWE_DIR
