import os
from pathlib import Path

STORAGE_DIR = Path(os.environ['STORAGE_DIR'])


###############################################
# Static data in this repo
###############################################
REPO_ROOT_DIR = Path(__file__).parent.parent.parent.absolute()

# Dir where static data is stored
REPO_STATIC_DATA_DIR = REPO_ROOT_DIR / 'static'
REPO_STATIC_COLORMAPS_INDEX_FP = REPO_STATIC_DATA_DIR / 'colormaps.json'
REPO_STATIC_VARIABLES_INDEX_FP = REPO_STATIC_DATA_DIR / 'variables.json'

# Dir where schemas are stored
# TODO: Move schemas in to ingest package?
REPO_STATIC_SCHEMAS_DIR = REPO_ROOT_DIR / 'schema'


###############################################
# Outputs generated by this program
###############################################

# Where this program will write temporary directories to store WIP ingest outputs
INGEST_WIP_DIR = STORAGE_DIR / 'ingest-wip'

# These are strings instead of Paths because they will be created inside temporary
# directories within INGEST_WIP_DIR
OUTPUT_REGIONS_SUBDIR = 'regions'
OUTPUT_REGIONS_SHAPES_SUBDIR = f'{OUTPUT_REGIONS_SUBDIR}/shapes'
OUTPUT_REGIONS_COGS_SUBDIR = f'{OUTPUT_REGIONS_SUBDIR}/cogs'
OUTPUT_LEGENDS_SUBDIR = 'legends'
OUTPUT_PLOTS_SUBDIR = 'plots'
OUTPUT_POINTS_SUBDIR = 'points'

# Where the live data goes after ingest is successful
OUTPUT_LIVE_DIR = STORAGE_DIR / 'live'


###############################################
# Inputs generated by upstream program
###############################################

INCOMING_DIR = STORAGE_DIR / 'incoming'
INCOMING_SWE_DIR = INCOMING_DIR / 'snow-water-equivalent'
INCOMING_SSP_DIR = INCOMING_DIR / 'snow-surface-properties'

INCOMING_REGIONS_DIR = INCOMING_SSP_DIR / 'regions'
INCOMING_REGIONS_ROOT_JSON = INCOMING_REGIONS_DIR / 'root.json'
INCOMING_TIF_DIR = INCOMING_SSP_DIR / 'geotiffs'
INCOMING_SHAPE_DIR = INCOMING_SSP_DIR / 'shapes'
INCOMING_PLOT_JSON_DIR = INCOMING_SSP_DIR / 'plots'
