from snow_today_webapp_ingest.constants.paths import REPO_STATIC_SCHEMAS_DIR

COLORMAPS_INDEX_SCHEMA_FP = REPO_STATIC_SCHEMAS_DIR / "colormapsIndex.json"
VARIABLES_INDEX_SCHEMA_FP = REPO_STATIC_SCHEMAS_DIR / "variablesIndex.json"

PLOT_DATA_SCHEMA_FP = REPO_STATIC_SCHEMAS_DIR / "plotData.json"

REGIONS_INDEX_SCHEMA_FP = REPO_STATIC_SCHEMAS_DIR / "regionsIndex.json"

SUB_REGION_COLLECTIONS_INDEX_SCHEMA_FP = (
    REPO_STATIC_SCHEMAS_DIR / "subRegionCollectionsIndex.json"
)
SUB_REGIONS_INDEX_SCHEMA_FP = REPO_STATIC_SCHEMAS_DIR / "subRegionsIndex.json"
SUB_REGIONS_HIERARCHY_SCHEMA_FP = REPO_STATIC_SCHEMAS_DIR / "subRegionsHierarchy.json"
