name: "Docker container image"

on:
  push:
    branches:
      - "main"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"


jobs:
  test:
    uses: "./.github/workflows/test.yml"

  # When a push to the default branch occurs, build and release "latest" images
  # When a tag `vX.Y.Z` push occurs, build and release images with that tag
  build-and-release-image:
    name: "Build and release the data server container image"
    needs:
      - "test"
    uses: "nsidc/.github/.github/workflows/build-and-publish-container-image.yml@main"
    secrets: "inherit"
    with:
      docker-file-name: "Dockerfile"
      docker-image-name: "nsidc/snow-today-webapp-server"

  # TODO: Decouple the two images
  build-and-release-ingest-image:
    name: "Build and release the ingest container image"
    needs:
      - "build-and-release-image"
    uses: "nsidc/.github/.github/workflows/build-and-publish-container-image.yml@main"
    secrets: "inherit"
    with:
      docker-file-name: "Dockerfile.ingest"
      docker-image-name: "nsidc/snow-today-webapp-server-ingest"
