name: "Test"

on:
  # The tests will be run on the main branch as part of the container build workflow.
  # push:
  #   branches:
  #     - "main"
  pull_request:
  # Enable running this workflow from the container build workflow:
  workflow_call:


# Default to bash in login mode; key to activating conda environment
# https://github.com/mamba-org/provision-with-micromamba#IMPORTANT
defaults:
  run:
    shell: "bash -l {0}"


jobs:
  test:
    name: "Run tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v3"

      - name: "Install Conda environment"
        uses: "mamba-org/setup-micromamba@v1"
        with:
          environment-file: "conda-lock.yml"
          # When using a lock-file, we have to set an environment name.
          environment-name: "ci"
          cache-environment: true
          # Increase this key to trigger cache invalidation
          cache-environment-key: 0

      - name: "Run tests"
        # TODO: Nox instead!
        run: "inv test"
